  # development:
  # access_key_id: 'AKIAJUHX7LZLFQ7FVRIA'
  # secret_access_key: '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'
  # production:
  # access_key_id: 'AKIAJUHX7LZLFQ7FVRIA'
  # secret_access_key: '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'
